### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by jackyuanjie1990** [butsugiri/chainer-abcnn#2]
Could you upload the data?

**Comment by butsugiri** [comment]
I deliberately didn't upload `data` dir, because I had no right to do it.
If you are looking for WikiQA dataset, you can download it from [here](https://www.microsoft.com/en-us/download/details.aspx?id=52419).
(I think you'll need to do some preprocessing in advance, so that trian/dev/test json files contains single example in each row.)

**Comment by jackyuanjie1990** [comment]
OK, Thank you very much!

**Comment by jackyuanjie1990** [comment]
Hi, I have another question. Did you encounter the problem about data imbalance when you classify QA pairs? Because the number of unrelated QA pairs in WikiQA is larger than related QA pairs. Thank you very much!

**Comment by butsugiri** [comment]
I am not sure what you mean by "related" pairs. Do you mean question-answer pairs with/without correct answer?

**Comment by jackyuanjie1990** [comment]
Yes

**Comment by butsugiri** [comment]
I followed the exact same setting as written on the paper of the ABCNN (section 5.1).

**Comment by jackyuanjie1990** [comment]
OK, thank you for your patient reply!
